# Generated by Django 2.2.2 on 2019-09-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=15, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('date_hired', models.DateField()),
                ('educational_attainment', models.CharField(max_length=200)),
                ('passport_no', models.CharField(max_length=30)),
                ('residencial_id', models.CharField(max_length=30)),
                ('res_type', models.IntegerField()),
                ('res_id_date_issued', models.DateField()),
                ('res_id_date_expires', models.DateField()),
                ('monthly_basic_salary', models.FloatField()),
                ('emp_craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Craft')),
            ],
        ),
        migrations.CreateModel(
            name='Service_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.FloatField()),
                ('date_of_service', models.DateField()),
                ('date_end', models.DateField()),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Craft')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Employees')),
            ],
        ),
    ]
