# Generated by Django 2.2.2 on 2019-09-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_record',
            name='craft',
        ),
        migrations.AddField(
            model_name='service_record',
            name='emp_no',
            field=models.CharField(default=1, max_length=50, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Employees')),
            preserve_default=False,
        ),
    ]
