# Generated by Django 2.2.2 on 2019-09-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20190913_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_record',
            name='emp_no',
            field=models.CharField(max_length=50),
        ),
    ]
