# Generated by Django 2.2.2 on 2019-09-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20190913_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_hired',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='res_id_date_expires',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='res_id_date_issued',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='service_record',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='service_record',
            name='date_of_service',
            field=models.DateTimeField(),
        ),
    ]
