# Generated by Django 2.2.2 on 2019-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20190913_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='res_id_date_expires',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='res_id_date_issued',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service_record',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service_record',
            name='date_of_service',
            field=models.DateField(),
        ),
    ]
